"project_identifier_env": CROWDIN_PROJECT_IDENTIFIER
"api_key_env" : CROWDIN_API_KEY
"base_path_env" : CROWDIN_BASE_PATH

"preserve_hierarchy": true

files: [
 {
  "source" : "/src/app/translations/default.pot",
  "dest": "/widgets/due-dates-calendar-widget/default.pot",
  "translation" : "/src/app/translations/due-dates-calendar-widget_%two_letters_code%.po",
 }
]
